// demo data for Tomsk MVP — Антисписание experiment (easy to revert)

import type { DiscountMapPin, PickupOffer } from "./types";

export const discountMapPins: DiscountMapPin[] = [
  {
    id: "pin-territoriya",
    restaurantId: "territoriya-kofe",
    restaurantName: "Территория Кофе",
    discountLabel: "−25%",
    x: 26,
    y: 40,
  },
  {
    id: "pin-surf",
    restaurantId: "surf-coffee-lamp",
    restaurantName: "Surf Coffee x Lamp",
    discountLabel: "−20%",
    x: 48,
    y: 26,
  },
  {
    id: "pin-dodo",
    restaurantId: "dodo-pizza",
    restaurantName: "Додо Пицца",
    discountLabel: "−25%",
    x: 70,
    y: 52,
  },
  {
    id: "pin-kintsugi",
    restaurantId: "kintsugi",
    restaurantName: "Кинцуги",
    discountLabel: "−20%",
    x: 36,
    y: 66,
  },
  {
    id: "pin-sibagro",
    restaurantId: "sibagro-gurme",
    restaurantName: "Сибагро Гурмэ",
    discountLabel: "−25%",
    x: 58,
    y: 36,
  },
  {
    id: "pin-snegiri",
    restaurantId: "snegiri",
    restaurantName: "Снегири",
    discountLabel: "−20%",
    x: 20,
    y: 56,
  },
  {
    id: "pin-pho",
    restaurantId: "pho-tigers",
    restaurantName: "Pho Tigers",
    discountLabel: "−20%",
    x: 76,
    y: 30,
  },
  {
    id: "pin-bezumno",
    restaurantId: "bezumno-shaurma",
    restaurantName: "Безумно.Крутая шаурма",
    discountLabel: "−15%",
    x: 44,
    y: 72,
  },
  {
    id: "pin-panda",
    restaurantId: "panda",
    restaurantName: "Панда",
    discountLabel: "−20%",
    x: 62,
    y: 58,
  },
];

export const pickupOffers: PickupOffer[] = [
  {
    id: "offer-1",
    restaurantId: "territoriya-kofe",
    restaurantName: "Территория Кофе",
    dishName: "Круассан миндальный",
    oldPrice: 240,
    newPrice: 180,
    discountPercent: 25,
    pickupWindow: "забрать до 21:00",
    availability: "осталось 4 порции",
    mapPinId: "pin-territoriya",
  },
  {
    id: "offer-2",
    restaurantId: "surf-coffee-lamp",
    restaurantName: "Surf Coffee x Lamp",
    dishName: "Чизкейк",
    oldPrice: 320,
    newPrice: 256,
    discountPercent: 20,
    pickupWindow: "забрать до 20:30",
    availability: "осталось 3 порции",
    mapPinId: "pin-surf",
  },
  {
    id: "offer-3",
    restaurantId: "dodo-pizza",
    restaurantName: "Додо Пицца",
    dishName: "Маргарита",
    oldPrice: 499,
    newPrice: 374,
    discountPercent: 25,
    pickupWindow: "до 22:00",
    availability: "осталось 5 порций",
    mapPinId: "pin-dodo",
  },
  {
    id: "offer-4",
    restaurantId: "kintsugi",
    restaurantName: "Кинцуги",
    dishName: "Моти манго",
    oldPrice: 260,
    newPrice: 208,
    discountPercent: 20,
    pickupWindow: "до 21:00",
    availability: "осталось 6 шт.",
    mapPinId: "pin-kintsugi",
  },
  {
    id: "offer-5",
    restaurantId: "sibagro-gurme",
    restaurantName: "Сибагро Гурмэ",
    dishName: "Чизкейк",
    oldPrice: 280,
    newPrice: 210,
    discountPercent: 25,
    pickupWindow: "до 21:30",
    availability: "осталось 2 порции",
    mapPinId: "pin-sibagro",
  },
  {
    id: "offer-6",
    restaurantId: "snegiri",
    restaurantName: "Снегири",
    dishName: "Медовик",
    oldPrice: 310,
    newPrice: 248,
    discountPercent: 20,
    pickupWindow: "до 22:00",
    availability: "осталось 4 шт.",
    mapPinId: "pin-snegiri",
  },
  {
    id: "offer-7",
    restaurantId: "pho-tigers",
    restaurantName: "Pho Tigers",
    dishName: "Bubble tea",
    oldPrice: 290,
    newPrice: 232,
    discountPercent: 20,
    pickupWindow: "до 21:00",
    availability: "осталось 5 порций",
    mapPinId: "pin-pho",
  },
  {
    id: "offer-8",
    restaurantId: "bezumno-shaurma",
    restaurantName: "Безумно.Крутая шаурма",
    dishName: "Комбо с напитком",
    oldPrice: 390,
    newPrice: 332,
    discountPercent: 15,
    pickupWindow: "до 22:30",
    availability: "осталось 3 порции",
    mapPinId: "pin-bezumno",
  },
  {
    id: "offer-9",
    restaurantId: "panda",
    restaurantName: "Панда",
    dishName: "Моти",
    oldPrice: 240,
    newPrice: 192,
    discountPercent: 20,
    pickupWindow: "до 21:00",
    availability: "осталось 4 шт.",
    mapPinId: "pin-panda",
  },
];
