// demo data for Tomsk MVP — not affiliated with listed venues
// Images: local placeholders only (/placeholder-venue.svg, /placeholder-dish.svg)

import type { Category, LiveUpdate, MenuItem, Restaurant } from "./types";

export const categories: Category[] = [
  { id: "1", label: "Все", icon: "✦" },
  { id: "2", label: "Завтраки", icon: "☀" },
  { id: "3", label: "Азия", icon: "◈" },
  { id: "4", label: "Вино", icon: "◇" },
  { id: "5", label: "Кофе", icon: "◎" },
  { id: "6", label: "Десерты", icon: "◐" },
];

export const restaurants: Restaurant[] = [
  {
    id: "territoriya-kofe",
    name: "Территория Кофе",
    cuisine: "Кофейня · завтраки · выпечка",
    description:
      "Авторский кофе, сырники и завтраки — живое меню до визита, бронь столика.",
    district: "Кировский · пр. Ленина, 10Б",
    rating: 4.8,
    averageCheck: 450,
    distance: "320 м",
    image: "/restaurants/territoria.png",
    liveStatus: "open",
    menuUpdatedAt: "2 мин назад",
    tags: ["живое меню", "бронь", "предзаказ"],
  },
  {
    id: "surf-coffee-lamp",
    name: "Surf Coffee x Lamp",
    cuisine: "Кофейня · specialty",
    description:
      "Спешелти-напитки и сэндвичи — предзаказ напитков к времени визита.",
    district: "Ленинский · ул. Усова, 11",
    rating: 4.7,
    averageCheck: 380,
    distance: "480 м",
    image: "/restaurants/surf.png",
    liveStatus: "busy",
    menuUpdatedAt: "4 мин назад",
    tags: ["live", "предзаказ", "скидки"],
  },
  {
    id: "dodo-pizza",
    name: "Додо Пицца",
    cuisine: "Пицца · паста",
    description:
      "Пицца и паста — актуальное меню, предзаказ к приходу без доставки.",
    district: "Октябрьский · ул. Иркутский тракт, 170",
    rating: 4.6,
    averageCheck: 650,
    distance: "1.2 км",
    image: "/restaurants/dodo.png",
    liveStatus: "open",
    menuUpdatedAt: "1 мин назад",
    tags: ["живое меню", "предзаказ"],
  },
  {
    id: "kintsugi",
    name: "Кинцуги",
    cuisine: "Японская · рамен · роллы",
    description:
      "Рамен, том ям и роллы — меню обновляется в течение дня, бронь столика.",
    district: "Советский · пр. Фрунзе, 242",
    rating: 4.9,
    averageCheck: 720,
    distance: "890 м",
    image: "/restaurants/kinzugi.png",
    liveStatus: "open",
    menuUpdatedAt: "3 мин назад",
    tags: ["живое меню", "бронь", "стоп-лист"],
  },
  {
    id: "sibagro-gurme",
    name: "Сибагро Гурмэ",
    cuisine: "Бургеры · гриль · мясное",
    description:
      "Бургеры и гриль из локального мяса — предзаказ блюд к времени.",
    district: "Ленинский · ул. Нахимова, 8",
    rating: 4.7,
    averageCheck: 580,
    distance: "650 м",
    image: "/restaurants/sibagro.png",
    liveStatus: "busy",
    menuUpdatedAt: "5 мин назад",
    tags: ["скидки", "предзаказ"],
  },
  {
    id: "snegiri",
    name: "Снегири",
    cuisine: "Ресторан · европейская",
    description:
      "Ужины и паста — живое меню, бронь столиков, блюда дня со скидкой.",
    district: "Кировский · ул. Красноармейская, 120",
    rating: 4.8,
    averageCheck: 1200,
    distance: "1.0 км",
    image: "/restaurants/snegiri.png",
    liveStatus: "open",
    menuUpdatedAt: "6 мин назад",
    tags: ["живое меню", "бронь", "вино"],
  },
  {
    id: "pho-tigers",
    name: "Pho Tigers",
    cuisine: "Вьетнамская · тайская",
    description:
      "Фо, том ям и пад тай — актуальные позиции и предзаказ к визиту.",
    district: "Октябрьский · ул. Алтайская, 20",
    rating: 4.7,
    averageCheck: 550,
    distance: "1.4 км",
    image: "/restaurants/tigers.png",
    liveStatus: "open",
    menuUpdatedAt: "2 мин назад",
    tags: ["live", "предзаказ", "скидки"],
  },
  {
    id: "bezumno-shaurma",
    name: "Безумно.Крутая шаурма",
    cuisine: "Шаурма · стритфуд",
    description:
      "Шаурма и комбо — быстрый предзаказ, заберите в заведении.",
    district: "Советский · пр. Мира, 26",
    rating: 4.5,
    averageCheck: 320,
    distance: "540 м",
    image: "/restaurants/bezumno.png",
    liveStatus: "busy",
    menuUpdatedAt: "только что",
    tags: ["предзаказ", "антифуд-вейст"],
  },
  {
    id: "panda",
    name: "Панда",
    cuisine: "Паназиатская · суши · вок",
    description:
      "Роллы, том ям и вок — живое меню, бронь и предзаказ блюд.",
    district: "Ленинский · ул. Герцена, 68",
    rating: 4.8,
    averageCheck: 680,
    distance: "760 м",
    image: "/restaurants/panda.png",
    liveStatus: "open",
    menuUpdatedAt: "4 мин назад",
    tags: ["живое меню", "бронь", "скидки"],
  },
];

export const menuItems: MenuItem[] = [
  // Территория Кофе
  {
    id: "tk1",
    restaurantId: "territoriya-kofe",
    name: "Кедровый латте",
    description: "350 мл · в наличии",
    price: 360,
    category: "Кофе",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "2 мин назад",
  },
  {
    id: "tk2",
    restaurantId: "territoriya-kofe",
    name: "Сырники со сметаной",
    description: "Домашние · в наличии",
    price: 290,
    category: "Завтраки",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "3 мин назад",
  },
  {
    id: "tk3",
    restaurantId: "territoriya-kofe",
    name: "Бейгл с форелью",
    description: "Заканчивается · осталось 3 порции",
    price: 550,
    category: "Завтраки",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "5 мин назад",
  },
  {
    id: "tk4",
    restaurantId: "territoriya-kofe",
    name: "Скрэмбл с колбасками",
    description: "Завтрак · в наличии",
    price: 470,
    category: "Завтраки",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "1 мин назад",
  },
  {
    id: "tk5",
    restaurantId: "territoriya-kofe",
    name: "Матча латте",
    description: "В наличии",
    price: 340,
    category: "Кофе",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "2 мин назад",
  },
  {
    id: "tk6",
    restaurantId: "territoriya-kofe",
    name: "Круассан миндальный",
    description: "Скидка −25% · до 21:00",
    price: 240,
    category: "Выпечка",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    isDiscount: true,
    discountPercent: 25,
    updatedAt: "8 мин назад",
  },
  // Surf Coffee x Lamp
  {
    id: "sc1",
    restaurantId: "surf-coffee-lamp",
    name: "Айс латте",
    description: "В наличии",
    price: 255,
    category: "Кофе",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "4 мин назад",
  },
  {
    id: "sc2",
    restaurantId: "surf-coffee-lamp",
    name: "Эспрессо-тоник",
    description: "В наличии",
    price: 325,
    category: "Кофе",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "3 мин назад",
  },
  {
    id: "sc3",
    restaurantId: "surf-coffee-lamp",
    name: "Флэт уайт",
    description: "В наличии",
    price: 260,
    category: "Кофе",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "2 мин назад",
  },
  {
    id: "sc4",
    restaurantId: "surf-coffee-lamp",
    name: "Сэндвич с индейкой",
    description: "Заканчивается · осталось 2 порции",
    price: 390,
    category: "Закуски",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "6 мин назад",
  },
  {
    id: "sc5",
    restaurantId: "surf-coffee-lamp",
    name: "Чизкейк",
    description: "Скидка −20% · до 20:30",
    price: 320,
    category: "Десерты",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    isDiscount: true,
    discountPercent: 20,
    updatedAt: "7 мин назад",
  },
  // Додо Пицца
  {
    id: "dd1",
    restaurantId: "dodo-pizza",
    name: "Пепперони",
    description: "Средняя · в наличии",
    price: 599,
    category: "Пицца",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "1 мин назад",
  },
  {
    id: "dd2",
    restaurantId: "dodo-pizza",
    name: "Додстер",
    description: "В наличии",
    price: 269,
    category: "Закуски",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "2 мин назад",
  },
  {
    id: "dd3",
    restaurantId: "dodo-pizza",
    name: "Карбонара",
    description: "В наличии",
    price: 649,
    category: "Паста",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "3 мин назад",
  },
  {
    id: "dd4",
    restaurantId: "dodo-pizza",
    name: "Чикен BBQ",
    description: "Заканчивается · осталось 4 порции",
    price: 729,
    category: "Пицца",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "5 мин назад",
  },
  {
    id: "dd5",
    restaurantId: "dodo-pizza",
    name: "Маргарита",
    description: "Скидка −25% · до 22:00",
    price: 499,
    category: "Пицца",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    isDiscount: true,
    discountPercent: 25,
    updatedAt: "6 мин назад",
  },
  // Кинцуги
  {
    id: "ki1",
    restaurantId: "kintsugi",
    name: "Рамен с говядиной",
    description: "В наличии",
    price: 590,
    category: "Основные",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "3 мин назад",
  },
  {
    id: "ki2",
    restaurantId: "kintsugi",
    name: "Том ям с креветкой",
    description: "В наличии",
    price: 690,
    category: "Супы",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "2 мин назад",
  },
  {
    id: "ki3",
    restaurantId: "kintsugi",
    name: "Гёдза с курицей",
    description: "Заканчивается · осталось 5 порций",
    price: 390,
    category: "Закуски",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "7 мин назад",
  },
  {
    id: "ki4",
    restaurantId: "kintsugi",
    name: "Ролл с лососем",
    description: "В наличии",
    price: 620,
    category: "Роллы",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "4 мин назад",
  },
  {
    id: "ki5",
    restaurantId: "kintsugi",
    name: "Моти манго",
    description: "Скидка −20% · до 21:00",
    price: 260,
    category: "Десерты",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    isDiscount: true,
    discountPercent: 20,
    updatedAt: "9 мин назад",
  },
  // Сибагро Гурмэ
  {
    id: "sg1",
    restaurantId: "sibagro-gurme",
    name: "Бургер с мраморной говядиной",
    description: "В наличии",
    price: 520,
    category: "Бургеры",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "5 мин назад",
  },
  {
    id: "sg2",
    restaurantId: "sibagro-gurme",
    name: "Стейк-салат",
    description: "Заканчивается · осталось 2 порции",
    price: 690,
    category: "Салаты",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "6 мин назад",
  },
  {
    id: "sg3",
    restaurantId: "sibagro-gurme",
    name: "Сэндвич с бужениной",
    description: "В наличии",
    price: 390,
    category: "Закуски",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "4 мин назад",
  },
  {
    id: "sg4",
    restaurantId: "sibagro-gurme",
    name: "Колбаски гриль",
    description: "В наличии",
    price: 560,
    category: "Гриль",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "3 мин назад",
  },
  {
    id: "sg5",
    restaurantId: "sibagro-gurme",
    name: "Чизкейк",
    description: "Скидка −25% · до 21:30",
    price: 280,
    category: "Десерты",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    isDiscount: true,
    discountPercent: 25,
    updatedAt: "10 мин назад",
  },
  // Снегири
  {
    id: "sn1",
    restaurantId: "snegiri",
    name: "Паста с грибами",
    description: "В наличии",
    price: 540,
    category: "Паста",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "6 мин назад",
  },
  {
    id: "sn2",
    restaurantId: "snegiri",
    name: "Утиная ножка с пюре",
    description: "Заканчивается · осталось 3 порции",
    price: 790,
    category: "Основные",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "8 мин назад",
  },
  {
    id: "sn3",
    restaurantId: "snegiri",
    name: "Салат с ростбифом",
    description: "В наличии",
    price: 620,
    category: "Салаты",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "4 мин назад",
  },
  {
    id: "sn4",
    restaurantId: "snegiri",
    name: "Брускетта с томатами",
    description: "В наличии",
    price: 360,
    category: "Закуски",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "5 мин назад",
  },
  {
    id: "sn5",
    restaurantId: "snegiri",
    name: "Медовик",
    description: "Скидка −20% · до 22:00",
    price: 310,
    category: "Десерты",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    isDiscount: true,
    discountPercent: 20,
    updatedAt: "7 мин назад",
  },
  // Pho Tigers
  {
    id: "pt1",
    restaurantId: "pho-tigers",
    name: "Фо Бо",
    description: "В наличии",
    price: 590,
    category: "Супы",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "2 мин назад",
  },
  {
    id: "pt2",
    restaurantId: "pho-tigers",
    name: "Том Ям",
    description: "В наличии",
    price: 690,
    category: "Супы",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "3 мин назад",
  },
  {
    id: "pt3",
    restaurantId: "pho-tigers",
    name: "Пад Тай",
    description: "В наличии",
    price: 520,
    category: "Основные",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "4 мин назад",
  },
  {
    id: "pt4",
    restaurantId: "pho-tigers",
    name: "Бао с курицей",
    description: "Заканчивается · осталось 4 порции",
    price: 340,
    category: "Закуски",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "6 мин назад",
  },
  {
    id: "pt5",
    restaurantId: "pho-tigers",
    name: "Bubble tea",
    description: "Скидка −20% · до 21:00",
    price: 290,
    category: "Напитки",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    isDiscount: true,
    discountPercent: 20,
    updatedAt: "8 мин назад",
  },
  // Безумно.Крутая шаурма
  {
    id: "bz1",
    restaurantId: "bezumno-shaurma",
    name: "Шаурма классическая",
    description: "В наличии",
    price: 260,
    category: "Шаурма",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "только что",
  },
  {
    id: "bz2",
    restaurantId: "bezumno-shaurma",
    name: "Шаурма сырная",
    description: "В наличии",
    price: 310,
    category: "Шаурма",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "1 мин назад",
  },
  {
    id: "bz3",
    restaurantId: "bezumno-shaurma",
    name: "Шаурма острая",
    description: "Заканчивается · осталось 3 порции",
    price: 290,
    category: "Шаурма",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "4 мин назад",
  },
  {
    id: "bz4",
    restaurantId: "bezumno-shaurma",
    name: "Картофель фри",
    description: "В наличии",
    price: 180,
    category: "Гарниры",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "2 мин назад",
  },
  {
    id: "bz5",
    restaurantId: "bezumno-shaurma",
    name: "Комбо с напитком",
    description: "Скидка −15% · до 22:30",
    price: 390,
    category: "Комбо",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    isDiscount: true,
    discountPercent: 15,
    updatedAt: "5 мин назад",
  },
  // Панда
  {
    id: "pd1",
    restaurantId: "panda",
    name: "Том Ям",
    description: "В наличии",
    price: 649,
    category: "Супы",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "4 мин назад",
  },
  {
    id: "pd2",
    restaurantId: "panda",
    name: "Ролл Филадельфия",
    description: "В наличии",
    price: 690,
    category: "Роллы",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "3 мин назад",
  },
  {
    id: "pd3",
    restaurantId: "panda",
    name: "Удон с курицей",
    description: "В наличии",
    price: 470,
    category: "Основные",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "2 мин назад",
  },
  {
    id: "pd4",
    restaurantId: "panda",
    name: "Вок с говядиной",
    description: "Заканчивается · осталось 2 порции",
    price: 560,
    category: "Вок",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    updatedAt: "6 мин назад",
  },
  {
    id: "pd5",
    restaurantId: "panda",
    name: "Моти",
    description: "Скидка −20% · до 21:00",
    price: 240,
    category: "Десерты",
    image: "/placeholder-dish.svg",
    isAvailable: true,
    isDiscount: true,
    discountPercent: 20,
    updatedAt: "7 мин назад",
  },
];

export const liveUpdates: LiveUpdate[] = [
  {
    id: "u1",
    restaurantId: "territoriya-kofe",
    restaurantName: "Территория Кофе",
    message: "Меню обновлено 2 мин назад",
    time: "2 мин",
    type: "menu",
  },
  {
    id: "u2",
    restaurantId: "kintsugi",
    restaurantName: "Кинцуги",
    message: "Гёдза с курицей — осталось 5 порций",
    time: "5 мин",
    type: "menu",
  },
  {
    id: "u3",
    restaurantId: "territoriya-kofe",
    restaurantName: "Территория Кофе",
    message: "Круассан миндальный — скидка до 21:00",
    time: "7 мин",
    type: "discount",
  },
  {
    id: "u4",
    restaurantId: "dodo-pizza",
    restaurantName: "Додо Пицца",
    message: "Чикен BBQ — позиция скоро скроется из заказа",
    time: "8 мин",
    type: "stop",
  },
  {
    id: "u5",
    restaurantId: "snegiri",
    restaurantName: "Снегири",
    message: "Утиная ножка — осталось 3 порции",
    time: "9 мин",
    type: "menu",
  },
  {
    id: "u6",
    restaurantId: "surf-coffee-lamp",
    restaurantName: "Surf Coffee x Lamp",
    message: "Чизкейк −20% · скидка до 20:30",
    time: "10 мин",
    type: "discount",
  },
  {
    id: "u7",
    restaurantId: "sibagro-gurme",
    restaurantName: "Сибагро Гурмэ",
    message: "Стейк-салат — осталось 2 порции",
    time: "11 мин",
    type: "menu",
  },
  {
    id: "u8",
    restaurantId: "bezumno-shaurma",
    restaurantName: "Безумно.Крутая шаурма",
    message: "Комбо с напитком −15% до 22:30",
    time: "12 мин",
    type: "discount",
  },
];

export const antiWasteDeals = [
  {
    id: "aw1",
    title: "Круассан миндальный",
    venue: "Территория Кофе",
    discount: "−25%",
    until: "до 21:00",
  },
  {
    id: "aw2",
    title: "Маргарита",
    venue: "Додо Пицца",
    discount: "−25%",
    until: "до 22:00",
  },
  {
    id: "aw3",
    title: "Медовик",
    venue: "Снегири",
    discount: "−20%",
    until: "осталось 4 шт.",
  },
];

export const featuredMenuVenue = {
  restaurantId: "territoriya-kofe",
  get name() {
    return (
      restaurants.find((r) => r.id === this.restaurantId)?.name ??
      "Территория Кофе"
    );
  },
  get menuUpdatedAt() {
    return (
      restaurants.find((r) => r.id === this.restaurantId)?.menuUpdatedAt ??
      "2 мин назад"
    );
  },
};

export function getRestaurantById(id: string): Restaurant | undefined {
  return restaurants.find((r) => r.id === id);
}

export function getMenuItemsByRestaurantId(restaurantId: string): MenuItem[] {
  return menuItems.filter((item) => item.restaurantId === restaurantId);
}
